# Generated by Django 4.2.3 on 2023-07-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
